name: Build FFmpeg with Nvidia Acceleration

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Release Tag (e.g., v1.0.0 or a date)'
        required: true
  schedule:
    - cron: '0 0 */14 * 1' # Runs every other Monday at 00:00 UTC

permissions:
  contents: write
  discussions: write
  
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Set Release Tag
        id: set_tag
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "release_tag=${{ github.event.inputs.tag_name }}" >> $GITHUB_OUTPUT
          else
            echo "release_tag=automated-build" >> $GITHUB_OUTPUT
          fi

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git nvidia-cuda-toolkit nvidia-cuda-dev libva-dev python3 python3-pip zip

      - name: Cache ffmpeg-build-script
        id: cache-build-script
        uses: actions/cache@v4.2.0
        with:
          path: ffmpeg-build-script
          key: ffmpeg-build-script-${{ github.sha }}

      - name: Clone ffmpeg-build-script
        if: steps.cache-build-script.outputs.cache-hit != 'true'
        run: git clone https://github.com/markus-perl/ffmpeg-build-script.git

      - name: Build FFmpeg
        working-directory: ffmpeg-build-script
        run: |
          CUDA_COMPUTE_CAPABILITY=75 SKIPINSTALL=yes SKIPRAV1E=yes VERBOSE=yes ./build-ffmpeg --enable-gpl-and-non-free --build --full-static

      - name: Archive Binaries
        run: |
          cd ffmpeg-build-script/workspace
          zip -r ffmpeg-bin.zip bin

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.5.0
        with:
          name: ffmpeg-artifact
          path: ffmpeg-build-script/workspace/ffmpeg-bin.zip

      - name: Release Binaries
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.set_tag.outputs.release_tag }}
          files: ffmpeg-build-script/workspace/ffmpeg-bin.zip
